name: rubocop

on: push

jobs:
  rubocop:
    name: 'RuboCop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install gems
        run: docker-compose run bundle install

      - name: Run rubocop
        run: docker-compose run bundle exec rubocop
