name: Ruby

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker
        shell: bash
        run: docker-compose build

      - name: Up docker
        shell: bash
        run: docker-compose up -d

      - name: Run RSpec
        shell: bash
        run:  |
          docker-compose run backend bundle exec rspec
        env:
          RAILS_ENV: test
      - name: Run RuboCop
        shell: bash
        run:  |
          docker-compose run backend bundle exec rubocop
