name: Ruby

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run backend rails db:create
      env:
        RAILS_ENV: test

    - name: Run RSpec
      shell: bash
      run:  |
        docker-compose run backend bundle exec rspec
      env:
        RAILS_ENV: test
    - name: Run RuboCop
      shell: bash
      run:  |
        docker-compose run backend bundle exec rubocop
