name: Ruby

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup DB
        shell: bash
        run: |
          docker-compose run --rm backend rails db:create
          docker-compose run --rm backend rails db:migrate

      - name: Run RSpec
        shell: bash
        run:  |
          docker-compose run backend bundle exec rspec
        env:
          RAILS_ENV: test
      - name: Run RuboCop
        shell: bash
        run:  |
          docker-compose run backend bundle exec rubocop
